#!/bin/sh

#SBATCH --job-name=featxtr_Schaefer
#SBATCH --output=/scratch/tyoeasley/WAPIAW3/brainrep_data/Schaefer_data/extract_feats/logs/featxtr_Schaefer_400_incomplete_subjs.out
#SBATCH --error=/scratch/tyoeasley/WAPIAW3/brainrep_data/Schaefer_data/extract_feats/logs/featxtr_Schaefer_400_incomplete_subjs.err
#SBATCH --time=23:55:00
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --mem=50GB

# constants
xtr_script="/scratch/tyoeasley/WAPIAW3/brainrep_data/Schaefer_data/extract_feats/feats_from_dtseries.py"

# user specs
group="/scratch/tyoeasley/WAPIAW3/brainrep_data/Schaefer_data/incomplete_subjs.csv"
groupname="incomplete_subjs"
dim=400

# derivatives
input_dir="/scratch/tyoeasley/WAPIAW3/brainrep_data/Schaefer_data/timeseries"

python ${xtr_script} -i ${input_dir} -d ${dim} -g ${group}


