#!/bin/sh
#SBATCH -J spNM_pfm
#SBATCH -o /scratch/tyoeasley/WAPIAW3/brainrep_data/PROFUMO_data/logs/submit_spNM_pfm.out
#SBATCH -e /scratch/tyoeasley/WAPIAW3/brainrep_data/PROFUMO_data/logs/submit_spNM_pfm.err
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --mem 300G
#SBATCH -t 23:55:00

creatspNM_src="/scratch/tyoeasley/WAPIAW3/brainrep_data/PROFUMO_data/make_spNMs_masked.py"

# list PROFUMO output folders
base_dir="/scratch/tyoeasley/WAPIAW3"
subj_group_flist="${base_dir}/subject_lists/lists_of_groups/code_disease_groups.txt"
out_PFM_path="/scratch/tyoeasley/WAPIAW3/brainrep_data/PROFUMO_data/out_PROFUMO"

#all_outputs=$( cat ${subj_group_flist} )
all_outputs=""

while IFS= read -r file_path
do
  file_name=$(basename "$file_path")
  base_name="${file_name%.*}"
  all_outputs="${all_outputs} $base_name"
done < "${subj_group_flist}"

for output in $all_outputs
do
        module load python
        source activate neuro
        python ${creatspNM_src} "${out_PFM_path}/${output}_25_Results.ppp"
        echo "${out_PFM_path}/${output}_25_Results.ppp/NetMats"
done

