#!/bin/sh
#SBATCH -J pfm
#SBATCH -o logs/pfm_out.o%j
#SBATCH -e logs/pfm_err.e%j
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --mem 100G
#SBATCH -t 5:00:00

# constants
base_dir="/scratch/tyoeasley/WAPIAW3"
mk_json="/scratch/tyoeasely/WAPIAW3/brainrep_data/PROFUMO_data/create_datalocations.sh"

# input parameters
subj_list="/scratch/tyoeasley/WAPIAW3/subject_lists/combined_subj_eid/example.csv"
src_json_type="\$( echo \"/scratch/tyoeasley/WAPIAW3/brainrep_data/PROFUMO_data/raw_data_subj_lists/\${groupname}_datalocations.json\" )"

# derivatives
groupname=$( basename $subj_list | cut -d. -f 1 )
src_json=$( ${mk_json} -b ${base_dir} -s ${subj_list} -j ${src_json_type} )

# PROFUMO parameters
module load singularity/3.5.2
container=/home/e.ty/profumo.sif
dim=25
mask=/scratch/tyoeasley/WAPIAW3/brainrep_data/final_GM_mask.nii.gz
output=/scratch/tyoeasley/WAPIAW3/brainrep_data/PROFUMO_data/out_PROFUMO/${groupname}_${dim}.pfm

singularity exec -B /scratch/tyoeasley/WAPIAW3 -B /ceph:/ceph ${container}  /opt/profumo/C++/PROFUMO ${src_json} ${dim} ${output} --useHRF 0.735 --hrfFile /opt/profumo/HRFs/Default.phrf --mask ${mask} --covModel Subject --dofCorrection 0.075
