#!/bin/sh

#SBATCH --job-name=dual_regression
#SBATCH --output=/scratch/tyoeasley/WAPIAW3/brainrep_data/ICA_data/dual_regression/example/ica300/groupICA300.dr/scripts+logs/dual_regression.out
#SBATCH --error=/scratch/tyoeasley/WAPIAW3/brainrep_data/ICA_data/dual_regression/example/ica300/groupICA300.dr/scripts+logs/dual_regression.err
#SBATCH --partition=small
#SBATCH --time=30:00:00
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --mem=50gb

	
/export/fsl/fsl-6.0.5/bin/fsl_glm -i /ceph/biobank/derivatives/melodic/sub-3069175/ses-01/sub-3069175_ses-01_melodic.ica/filtered_func_data_clean_MNI152 -d /scratch/tyoeasley/WAPIAW3/brainrep_data/ICA_data/melodic_output/example/ica300/melodic_IC -o /scratch/tyoeasley/WAPIAW3/brainrep_data/ICA_data/dual_regression/example/ica300/groupICA300.dr/dr_stage1_subject00009.txt --demean -m /scratch/tyoeasley/WAPIAW3/brainrep_data/ICA_data/dual_regression/example/ica300/groupICA300.dr/mask  
         /export/fsl/fsl-6.0.5/bin/fsl_glm -i /ceph/biobank/derivatives/melodic/sub-3069175/ses-01/sub-3069175_ses-01_melodic.ica/filtered_func_data_clean_MNI152 -d /scratch/tyoeasley/WAPIAW3/brainrep_data/ICA_data/dual_regression/example/ica300/groupICA300.dr/dr_stage1_subject00009.txt -o /scratch/tyoeasley/WAPIAW3/brainrep_data/ICA_data/dual_regression/example/ica300/groupICA300.dr/dr_stage2_subject00009 --out_z=/scratch/tyoeasley/WAPIAW3/brainrep_data/ICA_data/dual_regression/example/ica300/groupICA300.dr/dr_stage2_subject00009_Z --demean -m /scratch/tyoeasley/WAPIAW3/brainrep_data/ICA_data/dual_regression/example/ica300/groupICA300.dr/mask --des_norm  
         /export/fsl/fsl-6.0.5/bin/fslsplit /scratch/tyoeasley/WAPIAW3/brainrep_data/ICA_data/dual_regression/example/ica300/groupICA300.dr/dr_stage2_subject00009 /scratch/tyoeasley/WAPIAW3/brainrep_data/ICA_data/dual_regression/example/ica300/groupICA300.dr/dr_stage2_subject00009_ic