#!/bin/sh

#SBATCH --job-name=featxtr_PROFUMO_dummy
#SBATCH --output=/scratch/tyoeasley/WAPIAW3/brainrep_data/PROFUMO_data/extract_feats/logs/featxtr_PROFUMO_dummy_25_example.out
#SBATCH --error=/scratch/tyoeasley/WAPIAW3/brainrep_data/PROFUMO_data/extract_feats/logs/featxtr_PROFUMO_dummy_25_example.err
#SBATCH --time=23:55:00
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --mem=50GB

# constants
xtr_script="/scratch/tyoeasley/WAPIAW3/brainrep_data/PROFUMO_data/extract_feats/feats_from_dtseries.py"

# user specs
group="/scratch/tyoeasley/WAPIAW3/subject_lists/combined_subj_eid/example.csv"
groupname="example"
dim=25

# derivatives
input_dir="/scratch/tyoeasley/WAPIAW3/brainrep_data/PROFUMO_data/out_PROFUMO/${groupname}_${dim}.pfm"

python ${xtr_script} -i ${input_dir} -d ${dim} -g ${group}


