#!/bin/sh
#SBATCH --job-name=ext_dts_schaefer
#SBATCH --output=/scratch/tyoeasley/brain_representations/schaefer/ext_ptseries/logs/ext_dts_%j.out
#SBATCH --error=/scratch/tyoeasley/brain_representations/schaefer/ext_ptseries/logs/ext_dts_%j.err
#SBATCH --time=23:55:00
#SBATCH --mem=50GB

ext_scr="/scratch/tyoeasley/WAPIAW3/brainrep_data/Schaefer_data/pull_schaefer_timeseries.py"

dim=400
networks=17
res=2

source /export/anaconda/anaconda3/anaconda3-2020.07/bin/activate neuro
python ${ext_scr} -d ${dim} -n ${networks} -i ${res}
