#!/bin/sh

#SBATCH --job-name=dual_reg_d300
#SBATCH --output=/scratch/tyoeasley/WAPIAW3/brainrep_data/ICA_data/logs/dual_reg_d300.out
#SBATCH --error=/scratch/tyoeasley/WAPIAW3/brainrep_data/ICA_data/logs/dual_reg_d300.err
#SBATCH --time=05:00:00
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --mem=50gb

# constants
base_dir="/scratch/tyoeasley/WAPIAW3"
mask_fpath="${base_dir}/brainrep_data/final_GM_mask.nii.gz" 
mk_descon="${base_dir}/brainrep_data/ICA_data/rand_design_con.py"
mk_flist="${base_dir}/brainrep_data/eid_to_fpath.sh"
fpath_pattern="/ceph/biobank/derivatives/melodic/sub-%s/ses-01/sub-%s_ses-01_melodic.ica/filtered_func_data_clean_MNI152.nii.gz"

# user specifications
dim=300
design_fpath_type="${base_dir}/brainrep_data/ICA_data/design300"
eid_list=/scratch/tyoeasley/WAPIAW3/subject_lists/match_eid/match_rmed_G93_eid_wapiaw.csv

# derivatives
outname=$( basename ${eid_list} | cut -d. -f 1)
melodic_out="${base_dir}/brainrep_data/ICA_data/melodic_output/${outname}/ica${dim}"
DR_out=${melodic_out/"melodic_output"/"dual_regression"}
data_flist="${base_dir}/brainrep_data/ICA_data/raw_data_subj_lists/${outname}.txt"
${mk_flist} -i ${eid_list} -o ${data_flist} -p ${fpath_pattern}
n_subj=$(cat ${data_flist} | wc -l )

python ${mk_descon} -n ${n_subj} --fpath_noext ${design_fpath_type}

# output
echo "pulling from subject list: ${eid_list}"
echo "pulling subject data from generalized filepath: ${fpath_pattern}"
echo "        (list of filenames of preprocessed data can be found in): ${data_flist}"
echo "computing with ${dim} dimensions"
echo "sending melodic outputs to: ${melodic_out}"
if ! [ -d ${melodic_out} ]
then
	mkdir -p ${melodic_out}
fi
echo "sending dual_regression outputs to: ${DR_out}"
if ! [ -d ${DR_out}/groupICA${dim}.dr ]
then
	mkdir -p ${DR_out}
fi
# FSL calls
module load fsl
export DISPLAY=:1

melodic -i ${data_flist} -o ${melodic_out} --tr=0.72 --nobet -a concat -m ${mask_fpath} --report --Oall -d ${dim}

FSL_slurm/dual_regression_slurm "${melodic_out}/melodic_IC.nii.gz" ${dim} "${design_fpath_type}.mat" "${design_fpath_type}.con" 0 "${DR_out}/groupICA${dim}.dr" $(cat ${data_flist})

