#!/bin/sh
#SBATCH -J all_dual_reg
#SBATCH -o logs/all_dual_reg.out
#SBATCH -e logs/all_dual_reg.err
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --mem 1G
#SBATCH -t 00:05:00

script_fpath="/scratch/tyoeasley/WAPIAW3/job_submission_portal/extraction_jobs/submit_DR-ICA_sbatch.sh"

base_dir="/scratch/tyoeasley/WAPIAW3"
ICA_dir="${base_dir}/brainrep_data/ICA_data"
sbatch_fpath="${ICA_dir}/do_dual_reg_batch"


dim_list_fpath="${ICA_dir}/ICA_dimlist.txt"
subj_group_flist="${base_dir}/subject_lists/lists_of_groups/code_disease_groups.txt"

${script_fpath} -b ${base_dir} -I ${ICA_dir} -f ${sbatch_fpath} -d ${dim_list_fpath} -s ${subj_group_flist}
