#!/bin/sh

#SBATCH --job-name=maskgen2
#SBATCH --output=/scratch/tyoeasley/WAPIAW3/brainrep_data/ICA_data/dual_regression/match_rmed_G8_eid_wapiaw/ica150/groupICA150.dr/scripts+logs/maskgen2.out
#SBATCH --error=/scratch/tyoeasley/WAPIAW3/brainrep_data/ICA_data/dual_regression/match_rmed_G8_eid_wapiaw/ica150/groupICA150.dr/scripts+logs/maskgen2.err
#SBATCH --partition=small
#SBATCH --time=5:00:00
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --mem=50gb

	
$FSLDIR/bin/fslmerge -t /scratch/tyoeasley/WAPIAW3/brainrep_data/ICA_data/dual_regression/match_rmed_G8_eid_wapiaw/ica150/groupICA150.dr/maskALL `$FSLDIR/bin/imglob /scratch/tyoeasley/WAPIAW3/brainrep_data/ICA_data/dual_regression/match_rmed_G8_eid_wapiaw/ica150/groupICA150.dr/mask_*`
$FSLDIR/bin/fslmaths /scratch/tyoeasley/WAPIAW3/brainrep_data/ICA_data/dual_regression/match_rmed_G8_eid_wapiaw/ica150/groupICA150.dr/maskALL -Tmin /scratch/tyoeasley/WAPIAW3/brainrep_data/ICA_data/dual_regression/match_rmed_G8_eid_wapiaw/ica150/groupICA150.dr/mask
$FSLDIR/bin/imrm /scratch/tyoeasley/WAPIAW3/brainrep_data/ICA_data/dual_regression/match_rmed_G8_eid_wapiaw/ica150/groupICA150.dr/mask_*
